### ISSUE TITLE
Shell Expansion eating all machine parts

### ISSUE THREAD

**Issue by NLZ** [Jacorb90/Prestige-Tree#13] opened 2021-05-04 23:36 UTC
In v1.2 Patch 1 there is a bug that if you buy Shell Expansion and you have twice it's cost of machine parts, then it will still buy only x1 Shell Expansion, but reduce your remaining machine parts to 0.

**Comment by GSUI5051** [comment] 2021-05-05 12:59
I found a way to solve this. 

In line 7439 of js/layers.js, add 2 slashes before everything. 

Result:
`//else player.mc.points = player.mc.points.sub(b.sub(n).sub(1).times(b.plus(n).plus(10)).times(-0.05).floor()).max(0);`

Additional Info: If you read the cost (or requirement) formula of Shell Expansion, the more Shell Expansion you have bought, the cost is higher. If you have twice of the cost, you can buy only 1 Shell Expansion.

**Comment by Jacorb90** [comment] 2021-05-05 19:11
Well, this issue itself seems to be caused by it spending too much Machine Parts, so instead of removing that line entirely, I'd much rather figure out a more accurate way to calculate the amount to spend. I'll see if I can come up with a fix today...

**Comment by Jacorb90** [comment] 2021-05-05 19:34
I'm gonna close this now since I've fixed it on my end, this fix will be available on the beta branch later today, and will be pushed to the main branch once v1.3 is released :)

**Closed as completed by Jacorb90** 2021-05-05 19:34 UTC

**Comment by GSUI5051** [comment] 2021-05-06 02:31
Maybe a Shell Expansion automator can be inplemented cuz no one likes red glowing on a node.

**Comment by TheOneWayTruth** [comment] 2022-07-14 10:24
It doesnt work for me.
Im playing
"v1.3 Patch 1
"
i can only buy one shell at once, and it resets my maschine parts to a weird number like 14.
